[package]
name = "patricia-trie"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie (Ethereum Style)"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
log = "0.3"
# rand = "0.4"
ethcore-bytes = { git = "https://github.com/oasislabs/parity", branch = "eauge/invoke/filter-on-transaction-address" }
ethereum-types = { git = "https://github.com/oasislabs/primitives", branch = "ekiden" }
keccak-hash = { git = "https://github.com/oasislabs/parity", branch = "eauge/invoke/filter-on-transaction-address" }
hashdb = { git = "https://github.com/oasislabs/parity", branch = "eauge/invoke/filter-on-transaction-address" }
rlp = { git = "https://github.com/oasislabs/parity", branch = "eauge/invoke/filter-on-transaction-address" }
triehash = { git = "https://github.com/oasislabs/parity", branch = "eauge/invoke/filter-on-transaction-address" }
memorydb = { git = "https://github.com/oasislabs/parity", branch = "eauge/invoke/filter-on-transaction-address" }

[dev-dependencies]
trie-standardmap = { git = "https://github.com/oasislabs/parity", branch = "eauge/invoke/filter-on-transaction-address" }
