[package]
name = "ethereum-api"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
build = "build.rs"

[dependencies]
ekiden-core = { git = "https://github.com/oasislabs/ekiden", branch = "jberci/feature/move-rust-client-utils" }
ethereum-types = { git = "https://github.com/oasislabs/primitives", branch = "ekiden" }
protobuf = "~2.0"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
ekiden-tools = { git = "https://github.com/oasislabs/ekiden", branch = "jberci/feature/move-rust-client-utils" }
