[package]
name = "evm-api"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
build = "build.rs"

[dependencies]
ekiden-core = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ethereum-types = { git = "https://github.com/ekiden/primitives", branch = "ekiden" }
protobuf = "~1.4"
serde = "1.0"
serde_derive = "1.0"
common-types = { git = "https://github.com/ekiden/parity", branch = "sterling" }

[build-dependencies]
ekiden-tools = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
