[package]
name = "runtime-ethereum-api"
version = "0.2.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
ekiden-runtime = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ethereum-types = { git = "https://github.com/oasislabs/primitives", branch = "ekiden" }
serde = "1.0.71"
serde_derive = "1.0"
